### ISSUE TITLE
Default placeholder is arabic

### ISSUE THREAD

**Issue by mitchiru** [Cognigy/WebchatWidget#66]
<img width="176" alt="Screenshot 2019-10-29 at 12 08 00" src="https://user-images.githubusercontent.com/892231/67762065-e0568f00-fa44-11e9-838f-dc6e7daa0af9.png">

**Comment by pedily** [comment]
Hey @mitchiru,

This text is being fetched from the endpoint configuration. 
As configured in `dist/index.html`, this Webchat embedding points to an Endpoint on our development environment, where the "placeholder" configuration was set to the text you saw.

It will not show up this way when you connect the Webchat to another Endpoint.
