### ISSUE TITLE
Facebook List Element CSS Customization

### ISSUE THREAD

**Issue by AlexTeusz** [Cognigy/WebchatWidget#86]
Hi @pedily, @kwinto and @Cesarcs7, 

if I am right, it is yet not possible to customize the style of the **Facebook List Element**. Can you add this functionality?

Thanks.

// Alex

**Comment by AlexTeusz** [comment]
Okay it is possible but it's not mentioned in the docs :)

**Comment by Cesarcs7** [comment]
It is documented, it is the last entry here in the CSS customization documentation page.
You can also check it in the Webchat templates messages customization CodeSandbox demo

https://github.com/Cognigy/WebchatWidget/blob/master/docs/css-customization.md
