### ISSUE TITLE
Persistent History is not working in Mozilla 68.5

### ISSUE THREAD

**Issue by sivaprasad9394k** [Cognigy/WebchatWidget#96]
Dear Team,
Persistent History is not working in mozilla and chat window itself not allowing users to enter some value. Web-chat experience across the page navigation.

**Link: https://codesandbox.io/s/local-persistent-history-0dvwm**

How will the previous conversion history will be pushed to the same chat window even after the user moves to different page?
Thank you.

**Comment by kwinto** [comment]
Hi Siva,

previous conversions history is stored in the local storage of the browser, therefore it can be loaded from any page of the same domain.

It also works fine in current version of Firefox for me. If you are still experience the issue feel free to reopen this issue.
